name: discourse component

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Timestamp Begin
      run: date

    - uses: actions/checkout@v1

    - name: Clone highlightjs-mlir
      uses: actions/checkout@v2
      with:
        repository: highlightjs/highlightjs-mlir
        ref: 'master'
        path: 'hljs_src'

    - name: Regenerate plugin
      run: (mkdir -p hljs_src/build && mkdir -p hljs_src/build/javascripts/discourse/api-initializers/ &&
            cd hljs_src/build &&
            echo 'import { apiInitializer } from "discourse/lib/api";' >>  javascripts/discourse/api-initializers/init-theme.js &&
            echo 'export default apiInitializer((api) => {'  >> javascripts/discourse/api-initializers/init-theme.js &&
            sed -e 's/hljs.registerLanguage/api.registerHighlightJSLanguage/' ../dist/mlir.min.js >> javascripts/discourse/api-initializers/init-theme.js &&
            echo '});' >> javascripts/discourse/api-initializers/init-theme.js &&
            sed -e 's/hljs.registerLanguage/api.registerHighlightJSLanguage/' ../dist/mlir.min.js &&
            cp ../../about.json ./)
            
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: component
        publish_dir: ./hljs_src/build
        force_orphan: true
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'

    - name: Timestamp End
      run: date
